
// Objective-C API for talking to the following Go packages
//
//	shellharbor.local/ioshelper/shellharborts
//
// File is generated by gomobile bind. Do not edit.
#ifndef __ShellHarborTS_FRAMEWORK_H__
#define __ShellHarborTS_FRAMEWORK_H__

#include "SHShellharborts.objc.h"
#include "Universe.objc.h"

#endif
