// Objective-C API for talking to shellharbor.local/ioshelper/shellharborts Go package.
//   gobind -lang=objc -prefix="SH" shellharbor.local/ioshelper/shellharborts
//
// File is generated by gobind. Do not edit.

#ifndef __SHShellharborts_H__
#define __SHShellharborts_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class SHShellharbortsProxy;

/**
 * Proxy owns one reusable tsnet node and any TCP forwarders opened through it.
Its exported surface intentionally uses only gomobile-compatible types.
 */
@interface SHShellharbortsProxy : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
/**
 * Forward opens the first free loopback port starting at startPort and routes
accepted TCP connections to targetHost:targetPort through tsnet.
 */
- (BOOL)forward:(NSString* _Nullable)targetHost targetPort:(long)targetPort startPort:(long)startPort ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * ForwardHTTPConnect exposes a loopback forwarder through an HTTP CONNECT proxy.
 */
- (BOOL)forwardHTTPConnect:(NSString* _Nullable)proxyHost proxyPort:(long)proxyPort targetHost:(NSString* _Nullable)targetHost targetPort:(long)targetPort startPort:(long)startPort ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * ForwardSOCKS5 exposes a loopback forwarder that connects through an existing
SOCKS5 proxy. Credentials are intentionally unsupported until the profile
model has a protected credential field.
 */
- (BOOL)forwardSOCKS5:(NSString* _Nullable)proxyHost proxyPort:(long)proxyPort targetHost:(NSString* _Nullable)targetHost targetPort:(long)targetPort startPort:(long)startPort ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * ForwardUDP opens the first free loopback UDP port starting at startPort and
routes datagrams to targetHost:targetPort through the reusable tsnet node.
Mosh uses a single connected UDP peer, so one forwarder can preserve its
bidirectional packet flow without exposing the tailnet identity to iOS.
 */
- (BOOL)forwardUDP:(NSString* _Nullable)targetHost targetPort:(long)targetPort startPort:(long)startPort ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)start:(NSString* _Nullable)stateDir hostname:(NSString* _Nullable)hostname loginServer:(NSString* _Nullable)loginServer authKey:(NSString* _Nullable)authKey error:(NSError* _Nullable* _Nullable)error;
- (void)stop;
@end

FOUNDATION_EXPORT SHShellharbortsProxy* _Nullable SHShellharbortsNewProxy(void);

#endif
